tls:
  options:
    default:
      minVersion: VersionTLS12
    mintls13:
      minVersion: VersionTLS13

  stores:
    default:
      defaultCertificate:
        certFile: /certs/local.solve.com.crt
        keyFile: /certs/local.solve.com.key
